---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ moodle_dependencies }}"
  retries: 5
  register: _install_deps
  until: _install_deps is success

- name: Ensure needed directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "www-data"
    group: "www-data"
  with_items:
    - /var/www/moodle
    - "{{ moodle_data_dir }}"

- name: Fetch moodle repository
  become: yes
  become_user: www-data
  git:
    repo: "https://git.in.moodle.com/moodle/moodle.git"
    dest: /var/www/moodle
    version: "{{ moodle_git_version }}"
